/**
 * `epg init-grabber` — turn an `epg.config.ts` into a `tv_grab_*` executable.
 *
 * The generated file is deliberately tiny: everything the protocol needs is in
 * `runXmltvGrabber`, and everything about the source is in the config it
 * imports, so there is nothing here for a user to maintain.
 */

import { chmod, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { GrabberError } from '../core/error.js';

/** Where the shim imports the grabber from — this package, whatever it is called. */
const PACKAGE = `${__PKG_NAME__}/tv-grab`;

/** The mode a file needs to be run by name. */
const EXECUTABLE = 0o755;

/**
 * What `tv_find_grabbers` and tvheadend look for when scanning `PATH`. A file
 * named anything else works when run directly, but is never discovered.
 */
const GRABBER_NAME = /^tv_grab_[a-z0-9_]+$/;

/** The country code in `tv_grab_<cc>[_<source>]`, by convention ISO 3166-1. */
const COUNTRY = /^tv_grab_([a-z]{2})(?:_|$)/;

// What XMLTV::Options accepts — mirrors the check in `tv-grab/run.ts`, applied
// here so a bad version is caught while writing the file rather than on the
// grabber's first run.
const VERSION = /^\d+(\.\d+){0,2}(_\d*)?$/;

export interface InitGrabberOptions {
  /** The executable's name, e.g. `tv_grab_sk_example`. */
  name: string;
  /** The configuration it will grab with; the shim is written beside it. */
  configFile: string;
  /** The line `--description` prints. Defaults to the country and the name. */
  description?: string;
  /**
   * The grabber's own version, as its `--version` reports it. Defaults to the
   * version of the project the config lives in, else `0.1.0`.
   */
  version?: string;
  /** Replace an existing file. */
  force?: boolean;
}

export interface InitGrabberResult {
  /** Where it was written. */
  file: string;
  /** Things that are not wrong, but are worth saying. */
  warnings: string[];
  /** What to do with it next. */
  hints: string[];
}

/**
 * `tv_grab_sk_example` → `Slovakia (tv_grab_sk_example)`, the shape the
 * reference grabbers use — the region first, the source in brackets to tell
 * two grabbers for one country apart.
 *
 * The country name comes from `Intl`, which has every region already; an
 * unassigned code comes back unchanged, which is still a better placeholder
 * than the bare name and is what `--description` exists to override.
 */
export function defaultDescription(name: string): string {
  const code = COUNTRY.exec(name)?.[1];

  if (code === undefined) {
    return name;
  }

  const region = code.toUpperCase();

  try {
    return `${new Intl.DisplayNames(['en'], { type: 'region' }).of(region) ?? region} (${name})`;
  } catch {
    return `${region} (${name})`;
  }
}

export interface ShimOptions {
  name: string;
  description: string;
  version: string;
  /** How the shim imports the config — a relative specifier. */
  config: string;
}

/**
 * The executable's source.
 *
 * Written with no top-level `import`/`export` and no `require`, which is what
 * makes one file work everywhere: an extensionless file is CommonJS on Node 20
 * and 21, is an ES module where Node detects module syntax, and follows the
 * nearest `package.json` in between — a dynamic import is the one form all
 * three agree on. It also resolves relative to this file rather than the
 * caller, so the grabber still finds its config through a symlink on `PATH`.
 */
export function grabberShim(options: ShimOptions): string {
  return `#!/usr/bin/env node
// ${options.name} — an XMLTV grabber over ${options.config}
//
// Generated by \`epg init-grabber\`. The protocol lives in the package and what
// it grabs lives in the config, so there is nothing to maintain here. The
// imports are dynamic on purpose: that is the one form a file with no
// extension can use whether Node reads it as CommonJS or as an ES module.
(async () => {
  const [{ runXmltvGrabber }, config] = await Promise.all([
    import(${JSON.stringify(PACKAGE)}),
    import(${JSON.stringify(options.config)}),
  ]);

  process.exitCode = await runXmltvGrabber(config.default, {
    description: ${JSON.stringify(options.description)},
    version: ${JSON.stringify(options.version)},
    // Fixed, so the configuration stays ~/.xmltv/${options.name}.conf however
    // this file is named or symlinked on the way here.
    grabberName: ${JSON.stringify(options.name)},
  });
})();
`;
}

async function exists(file: string): Promise<boolean> {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

/**
 * The version of the project the config lives in — a better default for the
 * grabber's own version than a constant, since the two are released together:
 * `tv_grab_sk_example --version` then reports what the project it came from
 * calls itself.
 *
 * Ignored unless it is a version XMLTV accepts, so a `1.2.3-beta.1` falls back
 * rather than being written out to fail on the grabber's first run.
 */
export async function projectVersion(dir: string): Promise<string | undefined> {
  try {
    const { version } = JSON.parse(await readFile(path.join(dir, 'package.json'), 'utf8')) as {
      version?: unknown;
    };

    return typeof version === 'string' && VERSION.test(version) ? version : undefined;
  } catch {
    return undefined;
  }
}

/** Write the grabber, and say what to do with it. */
export async function initGrabber(options: InitGrabberOptions): Promise<InitGrabberResult> {
  // Beside the configuration, which is what keeps the import in the shim a
  // plain relative specifier — and one that survives being symlinked.
  const dir = path.dirname(options.configFile);
  const file = path.join(dir, options.name);
  const version = options.version ?? (await projectVersion(dir)) ?? '0.1.0';

  if (!VERSION.test(version)) {
    throw new GrabberError(`Invalid grabber version "${version}" (expected x, x.y or x.y.z)`);
  }

  if (!options.force && (await exists(file))) {
    throw new GrabberError(`${file} already exists; pass --force to replace it`);
  }

  await writeFile(
    file,
    grabberShim({
      name: options.name,
      description: options.description ?? defaultDescription(options.name),
      version,
      config: `./${path.basename(options.configFile)}`,
    }),
    'utf8',
  );

  // It is run by name, so it has to be executable — the one step a user would
  // otherwise have to be told about.
  await chmod(file, EXECUTABLE);

  return {
    file,
    warnings: GRABBER_NAME.test(options.name)
      ? []
      : [
          `Warning: "${options.name}" is not named tv_grab_<country>[_<source>], so` +
            ` tv_find_grabbers and tvheadend will not find it on PATH`,
        ],
    hints: [
      '',
      'Put it on your PATH, then configure it:',
      `  ln -s ${file} ~/.local/bin/${options.name}`,
      `  ${options.name} --configure`,
      `  ${options.name} --days 2 --quiet > guide.xml`,
      '',
      // Found the hard way: a grabber is run from wherever the caller happens
      // to be — tvheadend uses its own — so a relative cache directory quietly
      // becomes a second cache, and every day is fetched again.
      'Note: paths in the config resolve against the working directory, and a grabber',
      'runs from anywhere. Make cache.dir absolute (e.g. with import.meta.dirname).',
    ],
  };
}
